### ISSUE TITLE
If an error is thrown inside a transaction, it will never propagate to the parent

### ISSUE THREAD

**Issue by lgrignon** [jazimabbas/mock-typeorm#5]
Given this code

```ts
  async getAllAds(): Promise<Ad[]> {

        await dataSource.transaction(async (entityManager: EntityManager) => {
            /// save 
            // fineOne
            // save...
            throw new Error('lll')  
        });
```

and this test 

```ts
it("returns ads from TypeORM", async () => {
            mockTypeOrm().onMock(Ad)
                .toReturn(ads, 'find')
                .toReturn(false, 'findOne')
                .toReturn(ads[0], 'findOne');

            try {
                await adQueries.getAllAds();
            } catch (e) {
                console.log("-->  ERROR CAUGHT")
            }
        });
```

Error is never caught.

I had to mock transaction by myself:
```ts
beforeEach(() => {

    mockTypeOrm().resetAll();
    (dataSource as any).transaction = <T>(callback: (entityManager: EntityManager) => Promise<T>) => {
        return callback(dataSource.manager);
    };

});
```

Hope this will help :)

**Comment by jazimabbas** [comment]
I'll look into this issue, I think I didn't implement this. But I'll double check.

**Comment by lgrignon** [comment]
Thank you for your answer @jazimabbas 

I feel like it's not a good idea having to adapt the code to make mock typeorm work. It sounds like a bug, isn't it? 
Your workaround is functional but I think I will stick to my first workaround which does not modify code, but only tests.

Do you think that's something you will want to fix in a near future, in a next version? If not I think it should at least be mentionned in the doc

**Comment by jazimabbas** [comment]
To be very honest, I don't have enough time, but I'll try to fix it in next version.
